AWSTemplateFormatVersion: 2010-09-09
Parameters:
  GitHubUser:
    Type: String

  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String
    Default: master
  CloudfrontDistributionId:
    Type: String
Resources:
  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    DependsOn:
      - GremlinBackendDeployApp
      - GremlinBackendDeploymentGroup 
      - BackendCodeBuildProject
      - FrontendCodeBuildProject 
    Properties:
      RoleArn: !ImportValue CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !ImportValue PipelineBucketName
      Stages:
      - Name: Source
        Actions:
          - InputArtifacts: []
            ActionTypeId:
              Version: '1'
              Owner: ThirdParty
              Category: Source
              Provider: GitHub
            OutputArtifacts:
              - Name: SourceOutput
            RunOrder: 1
            Configuration:
              Owner: !Ref GitHubUser
              Repo: !Ref GitHubRepo
              PollForSourceChanges: 'false'
              Branch: !Ref GitHubBranch
              OAuthToken: '{{resolve:secretsmanager:MyGithubSecret:SecretString:token}}'
            Name: ApplicationSource
      - Name: Build
        Actions:
          - Name: BackendBuild
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            InputArtifacts:
              - Name: SourceOutput
            OutputArtifacts:
              - Name: BackendBuildOutput
            Configuration:
              ProjectName: !Ref BackendCodeBuildProject
          - Name: FrontendBuild
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            InputArtifacts:
              - Name: SourceOutput
            OutputArtifacts:
              - Name: FrontendBuildOutput
            Configuration:
              ProjectName: !Ref FrontendCodeBuildProject
      - Name: Deploy
        Actions:
          - Name: DeployBackend
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CodeDeploy
              Version: '1'
            InputArtifacts:
              - Name: BackendBuildOutput
            Configuration:
              ApplicationName: !Ref GremlinBackendDeployApp
              DeploymentGroupName: !Ref GremlinBackendDeploymentGroup
          - Name: DeployFrontend
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: S3
              Version: '1'
            InputArtifacts:
              - Name: FrontendBuildOutput
            Configuration:
              BucketName: !ImportValue FrontendBucketName
              Extract: true

  #Backend CodeDeploy
  GremlinBackendDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server

  #CodeDeploy BackendGroup
  GremlinBackendDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref GremlinBackendDeployApp
      DeploymentGroupName: "GremlinBackendDeploymentGroup"
      ServiceRoleArn: !ImportValue CodeDeployServiceRoleArn
      DeploymentConfigName: "CodeDeployDefault.AllAtOnce"
  
  #Backend CodeBuild
  BackendCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "BackendCodeBuild"
      ServiceRole: !ImportValue CodeBuildServiceRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PriviligedMode: true
        Image: "aws/codebuild/standard:5.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: REPOSITORY_NAME
            Value: !ImportValue ECRRepositoryName
          - Name: REPOSITORY_URI
            Value: !ImportValue ECRRepositoryUri

  #Frontend CodeBuild
  FrontendCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "FrontendCodeBuild"
      ServiceRole: !ImportValue CodeBuildServiceRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-frontend.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PriviligedMode: true
        Image: "aws/codebuild/standard:5.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: VITE_APP_BACKEND_URL
            Value: '{{resolve:ssm:/gremlin-eye/VITE_APP_BACKEND_URL}}'
            Type: PLAINTEXT
          - Name: CLOUDFRONT_DISTRIBUTION_ID
            Value: !Ref CloudfrontDistributionId
            Type: PLAINTEXT