AWSTemplateFormatVersion: 2010-09-09
Parameters:
  GitHubUser:
    Type: String

  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String
    Default: master
  CloudfrontDistributionId:
    Type: String
  CodeStarConnectionArn:
    Type: String
  ECSClusterName:
    Type: String
  ECSServiceName:
    Type: String
Resources:
  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    DependsOn:
      - BackendCodeBuildProject
      - FrontendCodeBuildProject 
    Properties:
      RoleArn: !ImportValue CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !ImportValue PipelineBucketName
      Stages:
      - Name: Source
        Actions:
          - Name: ApplicationSource
            InputArtifacts: []
            ActionTypeId:
              Version: '1'
              Owner: AWS
              Category: Source
              Provider: CodeStarSourceConnection
            OutputArtifacts:
              - Name: SourceOutput
            RunOrder: 1
            Configuration:
              BranchName: !Ref GitHubBranch
              ConnectionArn: !Ref CodeStarConnectionArn
              FullRepositoryId:
                Fn::Sub:
                  - "${OwnerName}/${RepoName}"
                  - OwnerName: !Ref GitHubUser
                    RepoName: !Ref GitHubRepo
      - Name: Build
        Actions:
          - Name: BackendBuild
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            InputArtifacts:
              - Name: SourceOutput
            OutputArtifacts:
              - Name: BackendBuildOutput
            Configuration:
              ProjectName: !Ref BackendCodeBuildProject
          - Name: FrontendBuild
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            InputArtifacts:
              - Name: SourceOutput
            OutputArtifacts:
              - Name: FrontendBuildOutput
            Configuration:
              ProjectName: !Ref FrontendCodeBuildProject
      - Name: Deploy
        Actions:
          - Name: DeployBackend
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: ECS
              Version: '1'
            InputArtifacts:
              - Name: BackendBuildOutput
            Configuration:
              ClusterName: !Ref ECSClusterName
              ServiceName: !Ref ECSServiceName
            RunOrder: 1
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            PullRequest:
              - Branches:
                  Includes:
                    - master
                Events:
                  - CLOSED
            SourceActionName: ApplicationSource

  #Backend CodeBuild
  BackendCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "BackendCodeBuild"
      ServiceRole: !ImportValue CodeBuildServiceRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        Image: "aws/codebuild/standard:5.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: REPOSITORY_NAME
            Value: !ImportValue ECRRepositoryName
          - Name: REPOSITORY_URI
            Value: !ImportValue ECRRepositoryUri

  #Frontend CodeBuild
  FrontendCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "FrontendCodeBuild"
      ServiceRole: !ImportValue CodeBuildServiceRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-frontend.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        Image: "aws/codebuild/standard:5.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: VITE_APP_BACKEND_URL
            Value: '{{resolve:ssm:/gremlin-eye/VITE_APP_BACKEND_URL}}'
            Type: PLAINTEXT
          - Name: CLOUDFRONT_DISTRIBUTION_ID
            Value: !Ref CloudfrontDistributionId
            Type: PLAINTEXT