AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ClusterName:
    Type: String
    Default: GremlinCluster
  ServiceName:
    Type: String
    Default: gremlin-service
  TaskFamily:
    Type: String
    Default: gremlin-task-definition
  TaskCpu:
    Type: Number
    Default: 256
    AllowedValues: [256, 512, 1024, 2048, 4096]
  TaskMemory:
    Type: Number
    Default: 512
    AllowedValues: [512, 1024, 2048, 4096, 8192, 16384]
    Description: Memory (in MiB) for the task
  DesiredCount:
    Type: Number
    Default: 2
  TwitchClientSecretName:
    Type: String
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: gremlin-eye-ecs-awslogs
      RetentionInDays: 30
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: ECSCluster
    Properties:
      Family: !Ref TaskFamily
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRoleArn
      TaskRoleArn: !ImportValue ECSInstanceRoleArn
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Cpu: !Ref TaskCpu
          Memory: !Ref TaskMemory
          Essential: true
          Image: !ImportValue ECRRepositoryUri
          LogConfiguration:
            LogDriver: awslogs
            Options:
              mode: non-blocking
              max-buffer-size: 25m
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: gremlin-eye-ecs-logs
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Environment:
            - Name: ASPNETCORE_URLS
              Value: http://+:443;http://+:80
            - Name: ASPNETCORE_ENVIRONMENT
              Value: Production
          Secrets:
            - Name: Authentication__Igdb__ClientId
              ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TwitchClientSecretName}:client-id::"
            - Name: Authentication__Igdb__ClientSecret
              ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TwitchClientSecretName}:client-secret::"
            - Name: ConnectionStrings__DefaultConnection
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/gremlin-eye/DB_CONNECTION_STRING"
            - Name: JwtSigningKey
              ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/gremlin-eye/JWT_SIGN_KEY:JwtSigningKey::"
      RuntimePlatform:
        OperatingSystemFamily: LINUX
  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSCluster
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      DeploymentController:
        Type: CODE_DEPLOY
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !ImportValue ECSSecurityGroupId
          Subnets:
            - !ImportValue PrivateSubnetAId
            - !ImportValue PrivateSubnetBId
      TaskDefinition: !Ref ECSTaskDefinition
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: 80
          TargetGroupArn: !ImportValue TargetGroupArn
  LoadBalancerHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: HTTP_302
      LoadBalancerArn: !ImportValue LoadBalancerArn
      Port: 80
      Protocol: HTTP
Outputs:
  ClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: ClusterName
  ServiceName:
    Value: !Ref ECSService
    Export:
      Name: ServiceName
  ECSTaskDefinitionArn:
    Value: !GetAtt ECSTaskDefinition.Arn
    Export:
      Name: ECSTaskDefinitionArn
