AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      TargetType: ip
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 10
      VpcId: !ImportValue VpcId
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Type: application
      Name: ALB-ECS-Gremlin-Service
      SecurityGroups:
        - !ImportValue PublicLoadBalancerSGId
      Subnets:
        - !ImportValue PublicSubnetAId
        - !ImportValue PublicSubnetBId
Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
    Export:
      Name: TargetGroupArn
  LoadBalancerArn:
    Value: !Ref LoadBalancer
    Export:
      Name: LoadBalancerArn
  LoadBalancerExternalUrl:
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: LoadBalancerExternalUrl