AWSTemplateVersion: "2010-09-09"
Parameters:
  GitHubUser:
    Type: String

  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String
    Default: main

  RDSMasterUsername:
    Type: String

  RDSPassword:
    Type: String

  HostedZoneId:
    Type: String
Resources:
  #S3 Bucket Stack
  S3BucketsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Template: "https://s3.amazonaws.com/gremlin-eye-infrastructure-templates/s3.yml"

  #ECRRepository Stack
  ECRRepositoryStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Template: "https://s3.amazonaws.com/gremlin-eye-infrastructure-templates/ecr.yml"

  #IAM Roles Stack
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - S3BucketsStack
      - ECRRepositoryStack 
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye-infrastructure-templates/iam.yml"
      Parameters:
        GitHubUser: !Ref GitHubUser
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch

  #Network Stack
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye-infrastructure-templates/network.yml"

  #LoadBalancer Stack
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMRolesStack
      - NetworkStack
    Properties:
      Template: "https://s3.amazonaws.com/gremlin-eye-infrastructure-templates/load-balancer.yml"

  #ECS Stack
  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - IAMRolesStack
      - ECRRepositoryStack
      - LoadBalancerStack 
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye-infrastructure-templates/ecs.yml"

  #RDS Stack
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - IAMRolesStack 
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye-infrastructure-templates/rds.yml"
      Parameters:
        RDSMasterUsername: !Ref RDSMasterUsername
        RDSPassword: !Ref RDSPassword

  #SSMParamStoreStack
  SSMParamStoreStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LoadBalancerStack 
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye-infrastructure/ssm-paramstore.yml"
      Parameters:
        ProjectName:
          Type: String
          Default: gremlin-eye
      JwtSigningKey:
        Type: String

  #CloudFront Stack
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3BucketsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye/infrastructure/cloudfront.yml"

  #Route53 Stack
  Route53Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CloudFrontStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye/infrastructure/route53.yml"
    Parameters:
      HostedIdZone: !Ref HostedZoneId

  #CodePipeline Stack
  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - S3BucketsStack
      - IAMRolesStack
      - ECSStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/gremlin-eye/infrastructure/ci-cd-pipeline.yml"
      Parameters:
        GitHubUser: !Ref GitHubUser
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch