AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ProjectName:
    Type: String
    Default: gremlin-eye
  RDSMasterUsername:
    Type: String
  DBName:
    Type: String
    Default: gremlindb

Resources:
  DBCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/${ProjectName}/DB_CREDENTIALS"
      GenerateSecretString:
        PasswordLength: 16
        ExcludeCharacters: '"@/\\$()[]=;|&"'
        SecretStringTemplate: !Sub |
          {
            "username": "${RDSMasterUsername}"
          }
        GenerateStringKey: "password"
  # DBConnectionString:
  #   Type: AWS::SSM::Parameter
  #   DependsOn: RDSInstance
  #   Properties:
  #     Name: !Sub "/${ProjectName}/DB_CONNECT_STRING"
  #     SecretString: !Join ["",
  #       [
  #         "Server=", !Join ["", [!GetAtt RDSInstance.Endpoint.Address, ""] ],
  #         ",", !GetAtt RDSInstance.Endpoint.Port,
  #         ";Database=", !Join ["", [!Ref DBName, ""] ],
  #         ";Trusted_Connection=False;TrustServerCertificate=True;User Id=", !Join ["", [!Sub "{{resolve:secretsmanager:/${ProjectName}/DB_CREDENTIALS:SecretString:username}}", ""] ],
  #         ";Password=", !Join ["", [!Sub "{{resolve:secretsmanager:/${ProjectName}/DB_CREDENTIALS:SecretString:password}}", ""] ],
  #         ";Connect Timeout=30;MultipleActiveResultSets=True;"
  #       ]
  #     ]
      
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBCredentials
    Properties:
      DBInstanceIdentifier: !Ref DBName
      DBInstanceClass: db.t3.micro
      Engine: sqlserver-ex
      LicenseModel: license-included
      MasterUsername: !Sub "{{resolve:secretsmanager:/${ProjectName}/DB_CREDENTIALS:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:/${ProjectName}/DB_CREDENTIALS:SecretString:password}}"
      AllocatedStorage: 20
      VPCSecurityGroups:
        - !ImportValue RDSSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      StorageType: gp2
      PubliclyAccessible: false
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: gremlindb-rds-private
      DBSubnetGroupDescription: An RDS Private Network
      SubnetIds:
        - !ImportValue PrivateSubnetAId
        - !ImportValue PrivateSubnetBId
Outputs:
  DBName:
    Value: !Ref DBName
    Export:
      Name: DBName
  DBEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: DBEndpoint
  DBPort:
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: DBPort